name: Jose
favicon: null
layout_spectrum: 0.3775280178524554
typography_spectrum: 0.7498877267353237
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5abcc8'
    - '#2a3779'
    - '#ebebeb'
    - '#a3d6d6'
    - '#9c9cb8'
  brandStrength: 0.4029338478576392
  lightness: 0.9185284159611911
  saturation: 0.9915814991109073
  rhythmicContrast: 0.38867486291565
purpose: []
